superstreamEngine:
  configMap:
    enable: true
    name: connection.conf
    fileData:
      fileName: connection.conf
      fileContent: | 
        connections:
        - name: connection
          type: confluent_kafka # available types : confluent_kafka, confluent_cloud_kafka, MSK, apache_kafka
          hosts: # list of Bootstrap servers
            - kafka.example.com:9092
          authentication:  # Specify one prefered method for connection
            method:
              noAuthentication:
                enabled: false
              ssl:
                enabled: false
                protocol: SSL
                ca: ""
                cert: ""
                key: ""
                insecureSkipVerify: true
              sasl:
                enabled: true  
                mechanism: PLAIN # sasl_mechanism options: "PLAIN", "SCRAM-SHA-512" 
                protocol: SASL_SSL
                username: 
                password: 
                tls:
                  enabled: false
                  ca: ""
                  cert: ""
                  key: ""
                  insecureSkipVerify: true
