{{- if not .Values.superstreamControlPlane.secret.useExisting -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.superstreamControlPlane.secret.name }}
  namespace: {{ include "superstream.namespace" . }}
type: Opaque
data: {{- ( include "superstreamCP.secret" . ) | nindent 2 -}}
{{- end -}}