apiVersion: v1
kind: Service
metadata:
  name: {{ include "superstream.fullname" . }}-control-plane
  labels:
    {{- include "superstream.labels" . | nindent 4 }}
spec:
  type: {{ .Values.superstreamControlPlane.service.type }}
  ports:
  - port: {{ .Values.superstreamControlPlane.service.port }}
    protocol: TCP
    targetPort: http
  selector:
    {{- include "superstream.selectorLabels" . | nindent 4 }}-control-plane