apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: superstream-control-plane
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: superstream-control-plane
    argocd.argoproj.io/instance: superstream-control-plane
  name: superstream-control-plane
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app.kubernetes.io/instance: superstream-control-plane
    app.kubernetes.io/name: superstream-control-plane